{% set version = "2021.7.8" %}
{% set sha256 = "d38eb990197248750182802ce790c5feb43c8a5ba9b58fcdfd264a10c65fcaf0" %}

package:
  name: restraintlib
  version: {{ version }}

source:
  url: https://github.com/mkowiel/restraintlib/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - cctbx-base >=2020.8
    - scikit-learn >0.21
    - pandas
    - six

test:
  imports:
    - restraintlib
  requires:
    - pytest
  source_files:
    - tests/*.py
    - tests/*.cif
    - tests/*.pdb
  commands:
    - pytest

about:
  home: https://github.com/mkowiel/restraintlib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bond length and angle restraints for DNA and RNA oligonucleotides

extra:
  recipe-maintainers:
    - mkowiel
    - dabrze
